# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCb5WCxPyKa8MsWC0v0UGPSZHN570g8h
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import json
import shap
from sklearn.metrics import roc_curve, auc

# Configure the page
st.set_page_config(page_title="COVID-19 Risk Stratification", layout="wide")
st.title("COVID-19 Patient Outcomes & Risk Stratification")

# Load data and models (cached for performance)
@st.cache_data
def load_data():
    return pd.read_csv('covid_data_sample.csv').dropna()

@st.cache_resource
def load_models():
    scaler = joblib.load('scaler.joblib')
    xgb_model = joblib.load('xgb_model.joblib')
    with open('metrics_results.json', 'r') as f:
        metrics_data = json.load(f)
    return scaler, xgb_model, metrics_data

df = load_data()
scaler, xgb_model, metrics_data = load_models()

feature_cols = ['AGE', 'SEX', 'PNEUMONIA', 'DIABETES', 'HYPERTENSION', 'OBESITY', 'COPD']
X = df[feature_cols]
y = df['DEATH']

# Create the 4 required tabs
tab1, tab2, tab3, tab4 = st.tabs([
    "Executive Summary",
    "Descriptive Analytics",
    "Model Performance",
    "Explainability & Prediction"
])

with tab1:
    st.header("Executive Summary")
    st.write("""
    **Dataset & Prediction Task:**
    This application utilizes a robust clinical dataset containing anonymized patient records to predict COVID-19 mortality outcomes. The core prediction task is a binary classification problem: determining whether a patient is likely to survive or pass away based on their demographic information (like age and sex) and pre-existing comorbidities (such as pneumonia, diabetes, and hypertension). The dataset provides a critical foundation for analyzing how these distinct health factors interact to influence patient vulnerability during a severe viral infection.

    **Why This Matters:**
    In high-stakes clinical environments, the ability to accurately stratify risk is essential for effective triage and resource allocation. By proactively identifying patients who face the highest mortality risks upon admission, healthcare providers can prioritize intensive care resources, ventilators, and specific therapeutic interventions for the most vulnerable populations. This predictive capability directly translates to better patient management and potentially saved lives in overwhelmed medical systems.

    **Approach & Findings:**
    Our approach involved training multiple machine learning algorithms, ranging from standard Logistic Regression to advanced ensemble methods like XGBoost and a Neural Network (MLP), to find the most accurate and interpretable model. We evaluated these models using metrics such as the F1 score to account for potential class imbalances. The analysis revealed that advanced age and the presence of pneumonia are the most significant drivers of mortality risk. Tree-based models, particularly XGBoost, provided the strongest predictive performance while maintaining the high level of interpretability required in medical decision-making.
    """)

with tab2:
    st.header("Descriptive Analytics")

    col1, col2 = st.columns(2)

    with col1:
        fig1, ax1 = plt.subplots()
        sns.countplot(data=df, x='DEATH', palette='viridis', ax=ax1)
        ax1.set_title("Distribution of Outcomes")
        st.pyplot(fig1)
        st.write("**Figure 1:** This chart displays the overall distribution of patient survival versus mortality within our dataset. It is crucial for identifying class imbalances, which informs our choice of evaluation metrics like the F1 score rather than relying solely on accuracy.")

        fig2, ax2 = plt.subplots()
        sns.boxplot(data=df, x='DEATH', y='AGE', palette='Set2', ax=ax2)
        ax2.set_title("Age Distribution by Outcome")
        st.pyplot(fig2)
        st.write("**Figure 2:** This boxplot illustrates the relationship between a patient's age and their mortality outcome. It clearly highlights that the deceased patient population tends to have a significantly higher median age compared to survivors.")

    with col2:
        fig3, ax3 = plt.subplots()
        sns.barplot(data=df, x='PNEUMONIA', y='DEATH', ci=None, ax=ax3)
        ax3.set_title("Mortality Rate by Pneumonia Status")
        st.pyplot(fig3)
        st.write("**Figure 3:** This bar chart reveals the drastic impact that a co-occurring pneumonia infection has on patient outcomes. Patients presenting with pneumonia exhibit a substantially elevated mortality rate, marking it as a critical risk factor.")

        fig4, ax4 = plt.subplots(figsize=(6, 5))
        sns.heatmap(df[feature_cols + ['DEATH']].corr(), annot=True, cmap='coolwarm', fmt=".2f", ax=ax4)
        ax4.set_title("Correlation Heatmap")
        st.pyplot(fig4)
        st.write("**Figure 4:** The correlation matrix quantifies the linear relationships between all continuous and binary features. It quickly identifies which independent variables, such as age and pneumonia, have the strongest positive correlation with the target mortality variable.")

with tab3:
    st.header("Model Performance")

    metrics_df = pd.DataFrame(metrics_data)
    st.dataframe(metrics_df, use_container_width=True)

    fig, ax = plt.subplots(figsize=(8, 4))
    sns.barplot(data=metrics_df, x='Model', y='F1', palette='Blues_d', ax=ax)
    plt.xticks(rotation=45)
    plt.title("Model Comparison by F1 Score")
    st.pyplot(fig)

    st.write("The summary table and bar chart above illustrate the comparative performance of our trained models on the held-out test set. Ensemble methods demonstrated superior performance in capturing the complex, non-linear relationships within the medical data.")

with tab4:
    st.header("Explainability & Interactive Prediction")

    st.subheader("Global Feature Importance (SHAP)")
    explainer = shap.TreeExplainer(xgb_model)
    X_scaled = scaler.transform(X)
    shap_values = explainer(X_scaled[:300])

    fig_summary, ax_summary = plt.subplots()
    shap.summary_plot(shap_values, X_scaled[:300], feature_names=feature_cols, show=False)
    st.pyplot(fig_summary)
    st.write("This summary plot ranks features by their overall impact on the model's predictions. The color indicates the feature value, showing how higher ages or the presence of comorbidities push the prediction towards higher mortality risk.")

    st.markdown("---")
    st.subheader("Interactive Patient Risk Assessment")

    col_input1, col_input2 = st.columns(2)
    with col_input1:
        input_age = st.slider("Age", 0, 100, 60)
        input_sex = st.selectbox("Sex (1=Female, 2=Male)", [1, 2])
        input_pneumonia = st.selectbox("Pneumonia (1=Yes, 2=No)", [1, 2])
        input_diabetes = st.selectbox("Diabetes (1=Yes, 2=No)", [1, 2])
    with col_input2:
        input_hypertension = st.selectbox("Hypertension (1=Yes, 2=No)", [1, 2])
        input_obesity = st.selectbox("Obesity (1=Yes, 2=No)", [1, 2])
        input_copd = st.selectbox("COPD (1=Yes, 2=No)", [1, 2])

    input_data = pd.DataFrame([[
        input_age, input_sex, input_pneumonia, input_diabetes,
        input_hypertension, input_obesity, input_copd
    ]], columns=feature_cols)

    input_scaled = scaler.transform(input_data)
    prob = xgb_model.predict_proba(input_scaled)[0][1]

    st.markdown(f"### Predicted Mortality Probability: **{prob:.2%}**")

    shap_val_single = explainer(input_scaled)
    shap_val_single.data = input_data.values
    shap_val_single.feature_names = feature_cols

    fig_waterfall, ax_waterfall = plt.subplots()
    shap.plots.waterfall(shap_val_single[0], show=False)
    st.pyplot(fig_waterfall)
    st.write("The waterfall plot breaks down this specific prediction. It illustrates exactly how each individual health factor mathematically increases or decreases the patient's baseline risk to arrive at the final probability.")