# -*- coding: utf-8 -*-
"""MSIS522 -  HW1 - Martin Guan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvEWM6zIeun2SiE5aExfpvGpPCIDWbSJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import json
import shap
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from xgboost import XGBClassifier
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load the full dataset and drop missing values
df_full = pd.read_csv('covid_data.csv').dropna()

# Sample 100,000 rows to optimize training time and memory usage
# random_state is set to 42 for reproducibility as required
df = df_full.sample(n=100000, random_state=42)

# Define the target variable and features
target_col = 'DEATH'
feature_cols = ['AGE', 'SEX', 'PNEUMONIA', 'DIABETES', 'HYPERTENSION', 'OBESITY', 'COPD']

X = df[feature_cols]
y = df[target_col]

# Target Distribution (Count plot showing class frequencies)
plt.figure(figsize=(6, 4))
sns.countplot(data=df, x=target_col, palette='viridis')
plt.title('Target Distribution (DEATH)')
plt.show()

# Feature Distributions and Relationships (At least 4 insightful visualizations)
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Plot 1: Age distribution by outcome using a boxplot
sns.boxplot(data=df, x=target_col, y='AGE', ax=axes[0, 0], palette='Set2')
axes[0, 0].set_title('Age Distribution by Outcome')

# Plot 2: Mortality rate by Pneumonia status
sns.barplot(data=df, x='PNEUMONIA', y=target_col, ax=axes[0, 1], ci=None)
axes[0, 1].set_title('Mortality Rate by Pneumonia')

# Plot 3: Age density across genders for both outcomes
sns.violinplot(data=df, x=target_col, y='AGE', hue='SEX', split=True, ax=axes[1, 0])
axes[1, 0].set_title('Age and Sex Distribution by Outcome')

# Plot 4: Mortality rate by Hypertension
sns.barplot(data=df, x='HYPERTENSION', y=target_col, ax=axes[1, 1], ci=None)
axes[1, 1].set_title('Mortality Rate by Hypertension')

plt.tight_layout()
plt.show()

# Correlation Heatmap
plt.figure(figsize=(8, 6))
corr_matrix = df[feature_cols + [target_col]].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", center=0)
plt.title('Correlation Heatmap')
plt.show()

# Data Preparation: Train/test split (70/30) and scaling
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

metrics_results = []

def evaluate_model(name, y_true, y_pred, y_prob):
    # Calculate required metrics: Accuracy, Precision, Recall, F1, AUC-ROC
    metrics = {
        "Model": name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1": f1_score(y_true, y_pred),
        "AUC-ROC": roc_auc_score(y_true, y_prob)
    }
    metrics_results.append(metrics)
    return metrics

# Logistic Regression Baseline
lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train_scaled, y_train)
evaluate_model("Logistic Regression", y_test, lr.predict(X_test_scaled), lr.predict_proba(X_test_scaled)[:, 1])

# Decision Tree with GridSearchCV
dt_params = {'max_depth': [3, 5, 7, 10], 'min_samples_leaf': [5, 10, 20]}
dt = GridSearchCV(DecisionTreeClassifier(random_state=42), dt_params, cv=5, scoring='f1')
dt.fit(X_train_scaled, y_train)
evaluate_model("Decision Tree", y_test, dt.predict(X_test_scaled), dt.predict_proba(X_test_scaled)[:, 1])

# Random Forest with GridSearchCV
rf_params = {'n_estimators': [50, 100], 'max_depth': [3, 5, 8]}
rf = GridSearchCV(RandomForestClassifier(random_state=42), rf_params, cv=5, scoring='f1', n_jobs=-1)
rf.fit(X_train_scaled, y_train)
evaluate_model("Random Forest", y_test, rf.predict(X_test_scaled), rf.predict_proba(X_test_scaled)[:, 1])

# XGBoost with GridSearchCV (using T4 GPU acceleration)
xgb_params = {'n_estimators': [50, 100], 'max_depth': [3, 5], 'learning_rate': [0.05, 0.1]}
xgb = GridSearchCV(XGBClassifier(random_state=42, eval_metric='logloss'), xgb_params, cv=5, scoring='f1')
xgb.fit(X_train_scaled, y_train)
evaluate_model("XGBoost", y_test, xgb.predict(X_test_scaled), xgb.predict_proba(X_test_scaled)[:, 1])

# Neural Network (MLP) architecture and training
mlp = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(128, activation='relu'),
    Dense(1, activation='sigmoid')
])
mlp.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
mlp.fit(X_train_scaled, y_train, epochs=20, batch_size=256, validation_split=0.2, verbose=0)

mlp_prob = mlp.predict(X_test_scaled).flatten()
evaluate_model("Neural Network", y_test, (mlp_prob > 0.5).astype(int), mlp_prob)

# Display model comparison summary
metrics_df = pd.DataFrame(metrics_results)
print(metrics_df)

# SHAP Analysis using the best-performing tree-based model
best_tree_model = xgb.best_estimator_
explainer = shap.TreeExplainer(best_tree_model)

# Compute SHAP values for a subset of the test data to prevent memory issues
shap_values = explainer(X_test_scaled[:500])

# 1. Summary plot (beeswarm) showing feature importance and impact direction
shap.summary_plot(shap_values, X_test_scaled[:500], feature_names=feature_cols)

# 2. Bar plot ranking features by mean absolute SHAP values
shap.summary_plot(shap_values, X_test_scaled[:500], feature_names=feature_cols, plot_type="bar")

# 3. Waterfall plot explaining a specific individual prediction
shap.plots.waterfall(shap_values[0])

from google.colab import files

# Save the scaler and pre-trained models required for Streamlit deployment
joblib.dump(scaler, 'scaler.joblib')
joblib.dump(lr, 'lr_model.joblib')
joblib.dump(dt.best_estimator_, 'dt_model.joblib')
joblib.dump(rf.best_estimator_, 'rf_model.joblib')
joblib.dump(xgb.best_estimator_, 'xgb_model.joblib')
mlp.save('mlp_model.keras')

# Save model comparison metrics to load in the app
with open('metrics_results.json', 'w') as f:
    json.dump(metrics_results, f)

# Automatically trigger downloads to the local machine
files.download('scaler.joblib')
files.download('lr_model.joblib')
files.download('dt_model.joblib')
files.download('rf_model.joblib')
files.download('xgb_model.joblib')
files.download('mlp_model.keras')
files.download('metrics_results.json')